### ISSUE TITLE
Does nothing when installed on Edge Version 111.0.1661.62 (Official build) (64-bit)

### ISSUE THREAD

**Issue by DerekFoulk** [leonardoneumann/DimPlus#18]
I installed this as instructed in Edge, which is chrome-based. My DIM interface remains the same. There is an error that explains that manifest v2 is being removed in 2023. Not sure if this is causing the extension to not work, but it seems like the extension is not working. If it's just updating the manifest json, then perhaps I can fix it. Dunno. Thanks

**Comment by DerekFoulk** [comment]
Nevermind about the not working... But the v2 to v3 issue remains :)

**Comment by leonardoneumann** [comment]
I have not tested in Edge, glad it works.
UI its been broken since Lightfall update of DIM. I will try to get a release out next week addressing those problems.
